CREATE SEQUENCE T_CONTATOS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_CONTATOS (
    ID INTEGER DEFAULT T_CONTATOS_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

INSERT INTO T_CONTATOS (ID, NOME, EMAIL, SENHA, DATA_NASCIMENTO)
VALUES (T_CONTATOS_SEQ.NEXTVAL,
        'John Doe',
        'john.doe@example.com',
        'senha123',
        TO_DATE('1990-05-15', 'YYYY-MM-DD')
       );
