name: Continuous Delivery

on:
    push:
        branches: "feature/main"

env:
  IMAGE_NAME: fiap-on-java-api
  AZURE_WEBAPP_NAME: fiap-on-java-api

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -
            name: Git Checkout
            uses: actions/checkout@v4

        -   name: Setup Java SDK
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '21'
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
            name: Build
            uses: docker/build-push-action@v6
            with:
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url  }}
        steps:
        -
            name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: fiap-on-java-api
              slot-name: 'production'
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              images: 'ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/fiap-on-java-api:latest'